version: '3.8'

services:
  nextjs:
    image: blog:latest
    container_name: blog.vineet.tech
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always 
    environment:
      - NODE_ENV=production 

networks:
  nextjs_network:
    driver: bridge
