version: '3.8'

services:
  nextjs:
    image: vineetagarwal2004/blog:latest
    container_name: blog

    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always 
    environment:
      - NODE_ENV=production 


